### ISSUE TITLE
i3 8100+msi b360m同样的配置，有加入核显的吗，没带独立显卡....

### ISSUE THREAD

**Issue by majnin** [shm007g/hackintosh_works#2]
新手 i3 8100 +msi b360 吃灰家用机没带独显 看到一脸的兴奋，下完发现注明没注入独显，整个人都谢了.....

**Comment by majnin** [comment]
一样配置，没有独立显卡rx570 只有 i3 8100的核显，这个plist能用吗

**Comment by shm007g** [comment]
可以亮机，但是核显无法很好的驱动，建议找其他config文件，应该很多。

**Comment by majnin** [comment]
处理器 英特尔 Core i3-8100 @ 3.60GHz 四核
主板 微星 B360M FIRE (MS-7B53) ( 英特尔 PCI 标准主机 CPU 桥 )
内存 8 GB ( 金泰克 DDR4 2667MHz )
主硬盘 台电 360GB A850 ( 360 GB / 固态硬盘 )
显卡 英特尔 UHD Graphics 630 ( 微星 )
声卡 瑞昱 ALC887 @ 英特尔 High Definition Audio 控制器
网卡 瑞昱 RTL8168/8111/8112 Gigabit Ethernet Controller / 微星
------------------------------------------------------------------------------------
上面是机子的配置，没法进入读条，也不太懂
[image: image.png]
倒是用
https://dev.tencent.com/u/sqlsec/p/Coding_clover/git/tree/master/台式机/i3-8100%2B
<https://dev.tencent.com/u/sqlsec/p/Coding_clover/git/tree/master/%E5%8F%B0%E5%BC%8F%E6%9C%BA/i3-8100%2B>
技嘉B360M-GAMMING-HD%2BUHD630%2B10.13.5
的pilst相近，但可能主板型号不同，能读完条但卡在logo 进不去安装。这个配置真没看到谁的了找不到了，只看到你的型号相同了，但是没法用。

Szymon <notifications@github.com> 于2019年7月2日周二 下午4:53写道：

**Comment by shm007g** [comment]
我觉得你的情况是bios没配置好。bios没配置好，不论什么配置都是安装不上的。你可以参考 https://www.tonymacx86.com/threads/unibeast-install-macos-mojave-on-any-supported-intel-based-pc.259381/ 配置下，选择uefi only 引导。这个配置可以装。

还要注意bios的版本是否比我的版本高，比我的版本高，此efi不支持。

建议在clover界面打开-v可以看到具体的出错信息，也方便你搜索错误。
